### ISSUE TITLE
Can't Install from github / go

### ISSUE THREAD

**Issue by ruevaughn** [danielthatcher/smuggles#1]
Hey Daniel, awesome tool. When I try to install it says 

```
go get: github.com/danielthatcher/smuggles@v0.3.0: parsing go.mod:
     module declares its path as: gitlab.com/dcthatch/smuggles
     but was required as: github.com/danielthatcher/smuggles
```

I'm guessing you moved to Gitlab?

This tool looks so awesome. I'll install it from source for now. Can't wait to try.

**Comment by sedorf** [comment]
its not exist in Gitlab

**Comment by ruevaughn** [comment]
Not publicly

**Comment by sedorf** [comment]
Hi ruevaughnn i see that you told " I'll install it from source for now. Can't wait to try. " 
can you please give me a copy ?

thanks bro

**Comment by sedorf** [comment]
1 - git clone https://github.com/danielthatcher/smuggles.git
2 - cd smuggles
3 - go build

**Comment by danielthatcher** [comment]
Hi @ruevaughn,

Thank you for reporting this issue. I haven't looked at this project for a while and only just noticed it, so that sorry for the delay.

It looks like go install pulls the latest tag rather than the latest commit (at least when the tags follow semver), so it was trying to install a tag from before I updated the module location. I've added another tage (`v0.4.0`), so `go get install github.com/danielthatcher/smuggles@v0.4.0` should now work.

I had some issues with go caching v0.3.0 as the latest verison, so if you run into those you can specify the tag directly:
```
go install -v github.com/danielthatcher/smuggles@v0.4.0
```
